CREATE DATABASE IF NOT EXISTS `rrs_test_dev`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rrs_test_dev`.`t_request_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `trace_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求流水号（全局唯一标识）',
  `sysid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '系统标识',
  `client_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户端IP地址',
  `url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求URL',
  `method` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'HTTP方法',
  `headers` text COLLATE utf8mb4_unicode_ci COMMENT '请求头信息（JSON格式存储）',
  `query_params` text COLLATE utf8mb4_unicode_ci COMMENT '查询参数（JSON格式存储）',
  `request_body` longtext COLLATE utf8mb4_unicode_ci COMMENT '请求体内容',
  `page_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '页面URL（来自X-Page-URL header）',
  `scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '场景ID（用于区分版本侧与执行批次）',
  `start_time` datetime NOT NULL COMMENT '请求开始时间',
  `start_time_ms` int(11) DEFAULT NULL COMMENT '执行开始毫秒时间',
  `end_time` datetime NOT NULL COMMENT '请求结束时间',
  `end_time_ms` int(11) DEFAULT NULL COMMENT '请求结束毫秒时间',
  `trace_stack_md5` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '调用链路追踪信息MD5',
  `status_code` int(11) DEFAULT NULL COMMENT '响应状态码',
  `response_body` longtext COLLATE utf8mb4_unicode_ci COMMENT '响应体内容',
  `duration` bigint(20) NOT NULL COMMENT '请求耗时（毫秒）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除（逻辑删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trace_id` (`trace_id`),
  KEY `idx_url` (`url`(156)),
  KEY `idx_method` (`method`),
  KEY `idx_start_time` (`start_time`,`start_time_ms`),
  KEY `idx_end_time` (`end_time`,`end_time_ms`),
  KEY `idx_sysid` (`sysid`),
  KEY `idx_sysid_time` (`sysid`,`end_time`,`end_time_ms`),
  KEY `idx_client_ip` (`client_ip`),
  KEY `idx_trace_stack_md5` (`trace_stack_md5`),
  KEY `idx_request_info_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='HTTP请求信息表';

CREATE TABLE IF NOT EXISTS `rrs_test_dev`.`t_request_compare_index` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `request_info_id` bigint(20) NOT NULL COMMENT '关联t_request_info.id',
  `trace_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求流水号',
  `sysid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '系统标识',
  `scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '场景ID',
  `env_tag` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '环境标识',
  `method` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'HTTP方法',
  `normalized_path` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标准化路径',
  `normalized_query` longtext COLLATE utf8mb4_unicode_ci COMMENT '标准化query参数',
  `normalized_body` longtext COLLATE utf8mb4_unicode_ci COMMENT '标准化body参数',
  `normalized_request_params` longtext COLLATE utf8mb4_unicode_ci COMMENT '标准化后的请求参数组合',
  `request_fingerprint` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求指纹',
  `request_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '请求摘要',
  `response_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '响应摘要',
  `parse_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SUCCESS' COMMENT '解析状态',
  `parse_error_msg` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '解析错误信息',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_info_id` (`request_info_id`),
  UNIQUE KEY `uk_trace_id` (`trace_id`),
  KEY `idx_scenario_fingerprint` (`scenario_id`,`request_fingerprint`),
  KEY `idx_sysid_method_path` (`sysid`,`method`,`normalized_path`(191)),
  KEY `idx_parse_status` (`parse_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='请求对比索引表';

CREATE TABLE IF NOT EXISTS `rrs_test_dev`.`t_regression_batch` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务编码',
  `batch_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务名称',
  `biz_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '业务名称',
  `old_scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '旧版本场景ID',
  `new_scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '新版本场景ID',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'INIT' COMMENT '任务状态',
  `total_sample_count` bigint(20) DEFAULT 0 COMMENT '总样本数',
  `pairable_count` bigint(20) DEFAULT 0 COMMENT '可配对数',
  `matched_count` bigint(20) DEFAULT 0 COMMENT '成功配对数',
  `same_count` bigint(20) DEFAULT 0 COMMENT '一致数',
  `diff_count` bigint(20) DEFAULT 0 COMMENT '差异数',
  `only_old_count` bigint(20) DEFAULT 0 COMMENT '仅旧版存在数',
  `only_new_count` bigint(20) DEFAULT 0 COMMENT '仅新版存在数',
  `invalid_count` bigint(20) DEFAULT 0 COMMENT '无效样本数',
  `block_count` bigint(20) DEFAULT 0 COMMENT '阻断差异数',
  `operator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发起人',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `remark` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_code` (`batch_code`),
  KEY `idx_old_scenario_id` (`old_scenario_id`),
  KEY `idx_new_scenario_id` (`new_scenario_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回归任务表';

CREATE TABLE IF NOT EXISTS `rrs_test_dev`.`t_compare_rule` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `rule_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则编码',
  `rule_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则名称',
  `scope_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作用域类型',
  `sysid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '系统标识',
  `api_path` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '接口路径',
  `scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '场景ID',
  `target_json_path` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标比较节点',
  `ignore_paths` longtext COLLATE utf8mb4_unicode_ci COMMENT '忽略路径JSON数组',
  `array_compare_mode` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '数组比较模式',
  `array_key_map` longtext COLLATE utf8mb4_unicode_ci COMMENT '数组主键配置JSON',
  `value_equivalence_rule` longtext COLLATE utf8mb4_unicode_ci COMMENT '值等价规则JSON',
  `severity_rule` longtext COLLATE utf8mb4_unicode_ci COMMENT '差异分级规则JSON',
  `priority` int(11) NOT NULL DEFAULT 100 COMMENT '优先级',
  `enabled` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `effective_start_time` datetime DEFAULT NULL COMMENT '生效开始时间',
  `effective_end_time` datetime DEFAULT NULL COMMENT '生效结束时间',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_code` (`rule_code`),
  KEY `idx_scope_priority` (`scope_type`,`priority`),
  KEY `idx_sysid_api_path` (`sysid`,`api_path`(191)),
  KEY `idx_scenario_id` (`scenario_id`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='比对规则表';

CREATE TABLE IF NOT EXISTS `rrs_test_dev`.`t_compare_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_id` bigint(20) NOT NULL COMMENT '所属回归任务ID',
  `old_scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '旧版本场景ID',
  `new_scenario_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '新版本场景ID',
  `request_fingerprint` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '请求指纹',
  `sysid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '系统标识',
  `method` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'HTTP方法',
  `api_path` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标准化接口路径',
  `old_request_info_id` bigint(20) DEFAULT NULL COMMENT '旧版请求ID',
  `new_request_info_id` bigint(20) DEFAULT NULL COMMENT '新版请求ID',
  `old_trace_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '旧版trace_id',
  `new_trace_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '新版trace_id',
  `pair_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '配对状态',
  `compare_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '比较状态',
  `diff_level` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '差异等级',
  `diff_count` int(11) DEFAULT 0 COMMENT '差异数量',
  `rule_snapshot` longtext COLLATE utf8mb4_unicode_ci COMMENT '规则快照JSON',
  `summary` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '差异摘要',
  `compare_time` datetime DEFAULT NULL COMMENT '比较时间',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_batch_fingerprint` (`batch_id`,`request_fingerprint`),
  KEY `idx_batch_compare_status` (`batch_id`,`compare_status`),
  KEY `idx_batch_diff_level` (`batch_id`,`diff_level`),
  KEY `idx_old_trace_id` (`old_trace_id`),
  KEY `idx_new_trace_id` (`new_trace_id`),
  KEY `idx_api_path` (`api_path`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='比对结果汇总表';

CREATE TABLE IF NOT EXISTS `rrs_test_dev`.`t_compare_result_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `result_id` bigint(20) NOT NULL COMMENT '对应比对结果ID',
  `batch_id` bigint(20) NOT NULL COMMENT '所属任务ID',
  `json_path` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '差异JSON路径',
  `diff_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '差异类型',
  `old_value` longtext COLLATE utf8mb4_unicode_ci COMMENT '旧值',
  `new_value` longtext COLLATE utf8mb4_unicode_ci COMMENT '新值',
  `severity` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '严重级别',
  `rule_source` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '规则来源',
  `is_ignored` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否忽略',
  `sort_no` int(11) DEFAULT NULL COMMENT '排序号',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_result_id` (`result_id`),
  KEY `idx_batch_id` (`batch_id`),
  KEY `idx_severity` (`severity`),
  KEY `idx_json_path` (`json_path`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='比对结果明细表';
